import React from 'react';
import { Box, Typography, Paper, Container } from '@mui/material';
import { Info, Shield, Zap, Users } from 'lucide-react';

const AboutPage: React.FC = () => {
  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Paper elevation={2} sx={{ p: 4, mb: 4 }}>
        <Typography variant="h3" component="h1" gutterBottom align="center">
          About Fake Checker
        </Typography>
        <Typography variant="h6" color="text.secondary" align="center" paragraph>
          Advanced AI Image Detection Technology
        </Typography>
      </Paper>

      <Box sx={{ display: 'grid', gap: 3, gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' } }}>
        <Paper elevation={1} sx={{ p: 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <Shield size={24} color="#1976d2" />
            <Typography variant="h5" sx={{ ml: 1 }}>
              What We Do
            </Typography>
          </Box>
          <Typography paragraph>
            Fake Checker uses advanced AI algorithms to detect whether an image was generated by artificial intelligence or created by humans. Our technology analyzes pixel patterns, compression artifacts, and other technical markers to provide accurate assessments.
          </Typography>
        </Paper>

        <Paper elevation={1} sx={{ p: 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <Zap size={24} color="#1976d2" />
            <Typography variant="h5" sx={{ ml: 1 }}>
              How It Works
            </Typography>
          </Box>
          <Typography paragraph>
            Our detection system analyzes multiple factors including edge consistency, noise patterns, compression markers, and generation artifacts. The AI model has been trained on millions of images to distinguish between human-created and AI-generated content.
          </Typography>
        </Paper>

        <Paper elevation={1} sx={{ p: 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <Users size={24} color="#1976d2" />
            <Typography variant="h5" sx={{ ml: 1 }}>
              Privacy First
            </Typography>
          </Box>
          <Typography paragraph>
            All image analysis is performed locally in your browser. Your images are never uploaded to our servers, ensuring complete privacy and security of your content. We believe in protecting your data while providing accurate results.
          </Typography>
        </Paper>

        <Paper elevation={1} sx={{ p: 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
            <Info size={24} color="#1976d2" />
            <Typography variant="h5" sx={{ ml: 1 }}>
              Use Cases
            </Typography>
          </Box>
          <Typography paragraph>
            Perfect for content creators, journalists, researchers, and anyone who needs to verify image authenticity. Whether you're fact-checking, content moderation, or academic research, Fake Checker provides reliable detection results.
          </Typography>
        </Paper>
      </Box>

      <Paper elevation={2} sx={{ p: 4, mt: 4, textAlign: 'center' }}>
        <Typography variant="h5" gutterBottom>
          Ready to Get Started?
        </Typography>
        <Typography color="text.secondary">
          Upload your images to begin AI detection analysis. No registration required.
        </Typography>
      </Paper>
    </Container>
  );
};

export default AboutPage;